#!/bin/bash
# DVC Helper Script for Backblaze B2
# Auto-generated by setup_b2_dvc.py

set -e

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v '#' | xargs)
fi

case "$1" in
    pull)
        echo "📥 Pulling data from B2..."
        dvc pull
        ;;
    push)
        echo "📤 Pushing data to B2..."
        dvc push
        ;;
    status)
        echo "📊 DVC Status:"
        dvc status
        ;;
    check)
        echo "🔍 Testing B2 connection..."
        python3 -c "
import os
import boto3
from botocore.exceptions import ClientError

try:
    s3 = boto3.client(
        's3',
        endpoint_url=os.getenv('B2_ENDPOINT'),
        aws_access_key_id=os.getenv('B2_KEY_ID'),
        aws_secret_access_key=os.getenv('B2_APPLICATION_KEY')
    )
    response = s3.list_objects_v2(Bucket=os.getenv('B2_BUCKET'), MaxKeys=5)
    print('✅ Connection successful!')
    print(f\"Bucket: {os.getenv('B2_BUCKET')}\")
    if 'Contents' in response:
        print(f'Files found: {len(response[\"Contents\"])}')
    else:
        print('Bucket is empty or no files in prefix')
except ClientError as e:
    print(f'❌ Connection failed: {e}')
    exit(1)
except Exception as e:
    print(f'❌ Error: {e}')
    exit(1)
"
        ;;
    *)
        echo "Usage: $0 {pull|push|status|check}"
        exit 1
        ;;
esac
