#!/bin/bash
# DVC Helper Script for Backblaze B2
# Auto-generated by setup_b2_dvc.py

set -e

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v '#' | xargs)
fi

case "$1" in
    pull)
        echo "📥 Pulling data from B2..."
        dvc pull
        ;;
    push)
        echo "📤 Pushing data to B2..."
        dvc push
        ;;
    status)
        echo "📊 DVC Status:"
        dvc status
        ;;
    check)
        echo "🔍 Testing B2 connection..."
        aws s3 ls s3://${B2_BUCKET}/ \
            --endpoint-url ${B2_ENDPOINT}
        ;;
    *)
        echo "Usage: $0 {pull|push|status|check}"
        exit 1
        ;;
esac
